spring.application.name=VisionService

# MongoDB
spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/visionservice?authSource=admin

# MinIO Configuration
app.minio.endpoint=http://localhost:9000
app.minio.access-key=admin
app.minio.secret-key=password
app.minio.bucket-name=user-photos

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password

# Spring AI Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llava
#spring.ai.ollama.chat.options.model=llava-phi3
#spring.ai.ollama.chat.options.model=llava:13b
#spring.ai.ollama.chat.options.model=llava:34b
#spring.ai.ollama.chat.options.model=minicpm-v
#spring.ai.ollama.chat.options.model=moondream
#spring.ai.ollama.chat.options.model=bakllava

# Qdrant Vector Store
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=photo-descriptions

# Spring AI Ollama Embedding
spring.ai.ollama.embedding.options.model=nomic-embed-text
